[project]
name = "mcps"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastmcp>=2.10.1",
    "openai>=1.93.0",
    "pandas>=2.3.0",
    "pulp>=3.2.1",
    "python-dotenv>=1.1.1",
    "wikipedia>=1.4.0",
]
